### ISSUE TITLE
Collaborate?

### ISSUE THREAD

**Issue by lox** [pivotal-cf/go-binmock#2]
Hi! I was inspired by binmock to write https://github.com/lox/bintest. It splits the process into a `proxy` package which is solely responsible for building binary proxies and communicating with the parent process (similar to binmock, except with streaming stdin/stdout/stderr) and then a mock package on top of it.

Would be keen to collaborate!

**Comment by tinygrasshopper** [comment]
We would be interested to add that functionality in. I am a bit unclear on what do you mean by streaming stdin/stdout/stderr, can you please specify the api interface you are thinking about.

Currently the mock binary speaks to the server over http to get the responses, this process would be interesting in the case of streaming.

**Comment by lox** [comment]
Check out my client for an idea of what I am talking about with streaming: https://github.com/lox/bintest/blob/master/proxy/data/client.go

Imagine mocking out something like a `git clone` that runs for quite a while and gradually outputs text. With `go-binmock`, the process blocks until output is finished. My server is here: https://github.com/lox/bintest/blob/master/proxy/server.go.
